alliance/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('alliance.views',
    url(r'^$', 'front_page'),

    url(r'^users/(?P<username>.+)/$', 'user_profile'),

    # Putting database primary keys in the URL isn't exactly pretty,
    # but it'll do for now
    url(r'^opportunities/(?P<pk>.+)/$', 'opportunity'),
)

alliance/models.py
from django.core.validators import MinValueValidator
from django.db import models


class Region(models.Model):
    """
    A geographical region associated with both users and opportunities.
    """
    label = models.CharField(max_length=40, unique=True)

    def __unicode__(self):
        return self.label

    class Meta:
        ordering = ('label',)


class Skill(models.Model):
    """
    A particular skill a musician has or an opportunity requires, like
    "jazz percussion" or "violin."
    """
    label = models.CharField(max_length=40, unique=True)

    def __unicode__(self):
        return self.label

    class Meta:
        ordering = ('label',)


class SkillLevel(models.Model):
    """
    Represents levels of proficiency. Users and opportunities are optionally
    associated with not only a skill (like "Piano") but a certain level of
    that skill (like "beginner" or "professional").
    """
    label = models.CharField(max_length=40, unique=True)
    order = models.SmallIntegerField(unique=True)

    def __unicode__(self):
        return self.label

    class Meta:
        ordering = ('-order', 'label')


class UserProfile(models.Model):
    """
    User profile data for this app.

    We shouldn't assume Django's AUTH_PROFILE_MODULE and User.get_profile()
    features will work for us -- a site may set those to some other app's
    model.
    """
    user = models.OneToOneField('auth.User')
    skills = models.ManyToManyField('alliance.Skill', blank=True,
        through='alliance.UserSkill')
    regions = models.ManyToManyField('alliance.Region', blank=True)

    def display_name(self):
        n = self.user.get_full_name()
        if not n:
            return self.user.username
        return n

    @models.permalink
    def get_absolute_url(self):
        return ('alliance.views.user_profile', [self.user.username])

    def __unicode__(self):
        return '%s Alliance profile' % self.user

    class Meta:
        ordering = ('user',)


class UserSkill(models.Model):
    """
    Intermediary model for the User-Skill many-to-many relationship.
    """
    user = models.ForeignKey('alliance.UserProfile')
    skill = models.ForeignKey('alliance.Skill')
    level = models.ForeignKey('alliance.SkillLevel', blank=True)


class Opportunity(models.Model):
    """
    A request for particular skills.
    """
    region = models.ForeignKey('alliance.Region')
    #reqs = models.ManyToManyField('alliance.Requirement')
    label = models.CharField(max_length=40)
    description = models.TextField()
    owner = models.ForeignKey('alliance.UserProfile')
    post_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.label

    class Meta:
        ordering = ('post_date', 'label')
        verbose_name_plural = 'opportunities'


class Requirement(models.Model):
    """
    Intermediary model for the Opportunity-Skill many-to-many relationship.
    """
    opportunity = models.ForeignKey('alliance.Opportunity')
    skill = models.ForeignKey('alliance.Skill')
    level = models.ForeignKey('alliance.SkillLevel', blank=True)
    count = models.PositiveIntegerField(blank=True, null=True,
        validators=[MinValueValidator(1)])
    takers = models.ManyToManyField('alliance.UserProfile', blank=True)

alliance/views.py
from django.shortcuts import get_object_or_404, render

from alliance.models import Opportunity, UserProfile

def front_page(request):
    profile = None
    if request.user.is_authenticated():
        try:
            profile = UserProfile.objects.get(user=request.user)
        except UserProfile.DoesNotExist:
            pass
    return render(request, 'alliance/front.html', {'profile': profile})


def opportunity(request, pk):
    opp = get_object_or_404(Opportunity, pk=pk)
    return render(request, 'alliance/opportunity.html', {'opp': opp})


def user_profile(request, username):
    profile = get_object_or_404(UserProfile, user__username=username)
    return render(request, 'alliance/profile.html', {'profile': profile})

alliance/templates/alliance/base.html
{% extends "base_site.html" %}

{% comment %}

This is Alliance's app-level base template. All other Alliance templates extend
this one. Site administrators may change the appearance of Alliance pages by
writing replacement templates and saving them in an alliance/ subdirectory of
one of the paths in Django's TEMPLATE_DIRS setting.

{% endcomment %}


{% load url from future %}


{% block body %}
<div id="alli_header">
    <div id="alli_branding">Music<span class="alli_trick">Ally</span></div>
    <div id="alli_ident">
    {% if user.is_authenticated %}
        {% if profile %}<a href="{{ profile.get_absolute_url }}">{% endif %}
        {{ user.get_full_name|default:user.username }}
        {% if profile %}</a>{% endif %}
        | <a href="{% url "django.contrib.auth.views.logout" %}">Log out</a>
    {% else %}
        <a href="{% url "django.contrib.auth.views.login" %}">Log in</a>
    {% endif %}
    </div>
</div>

{% block content %}{% endblock content %}
{% endblock body %}

alliance/templates/alliance/front.html
{% extends "alliance/base.html" %}

{% load url from future %}

{% block title %}Alliance{% endblock title %}


{% block content %}

{% if profile %}
<dl>

<dt>Regions</dt>
{% for location in profile.regions.all %}
<dd>{{ location.label }}</dd>
{% empty %}
<dd><i>None</i></dd>
{% endfor %}

<dt>Skills</dt>
{% for skill in profile.skills.all %}
<dd>{{ skill.label }}</dd>
{% empty %}
<dd><i>None</i></dd>
{% endfor %}

<dt>Owned opportunities</dt>
{% for opp in profile.opportunity_set.all %}
<dd><a href="{% url "alliance.views.opportunity" opp.pk %}">
    {{ opp.label }}</a></dd>
{% empty %}
<dd><i>None</i></dd>
{% endfor %}

<dt>Interested opportunities</dt>
{% for req in profile.requirement_set.all %}
<dd><a href="{% url "alliance.views.opportunity" pk=req.pk %}">
    {{ req.opportunity.label }}</a> &mdash; {{ req.skill.label }}</dd>
{% empty %}
<dd><i>None</i></dd>
{% endfor %}

</dl>
{% else %}

<p>You don't seem to have an Alliance profile.</p>

{% endif %}

{% endblock content %}

alliance/templates/alliance/opportunity.html
{% extends "alliance/base.html" %}

{% load humanize %}
{% load url from future %}


{% block title %}{{ opp.label }}{% endblock title %}

{% block content %}
<dl>
    <dt>Label</dt>
    <dd>{{ opp.label }}</dd>

    <dt>Owner</dt>
    <dd>
    <a href="{{ opp.owner.get_absolute_url }}">{{ opp.owner.display_name }}</a>
    </dd>
    </dt>

    <dt>Region</dt>
    <dd>{{ opp.region.label|default:"(None)" }}</dd>

    <dt>Description</dt>
    <dd>{{ opp.description }}</dd>

    <dt>Posting date</dt>
    <dd>{{ opp.post_date }}</dd>

    <dt>Requested skills</dt>
    <dd><ul>
    {% for req in opp.requirement_set.all %}
    <li>
    {{ req.count|apnumber|title }} {{ req.skill }} ({{ req.level }})
    {% for taker in req.takers.all %}
        {% if forloop.first %}&mdash;{% else %}/{% endif %}
        <a href="{{ taker.get_absolute_url }}">{{ taker.display_name }}</a>
    {% endfor %}
</li>
{% endfor %}
</ul></dd>

</dl>
{% endblock content %}

alliance/templates/alliance/profile.html
{% extends "alliance/base.html" %}

{% load url from future %}

{% block title %}{{ profile.display_name }}{% endblock title %}


{% block content %}
<dl>
    <dt>Username</dt>
    <dd>{{ profile.user.username }}</dd>

    <dt>Full name</dt>
    <dd>
    {% if profile.user.get_full_name %}
        {{ profile.user.get_full_name }}
    {% else %}
        <i>None given</i>
    {%endif %}
    </dd>

    <dt>Skills</dt>
    <dd><ul>
    {% for userskill in profile.userskill_set.all %}
        <li>{{ userskill.skill.label }} &mdash; {{ userskill.level }}</li>
    {% empty %}
        <li><i>None</i></li>
    {% endfor %}
    </ul></dd>

    <dt>Owned opportunities</dt>
    {% for opp in profile.opportunity_set.all %}
        <dd><a href="{% url "alliance.views.opportunity" pk=opp.pk %}">
            {{ opp.label }}</a></dd>
    {% empty %}
        <dd><i>None</i></dd>
    {% endfor %}

    <dt>Interested opportunities</dt>
    {% for req in profile.requirement_set.all %}
        <dd><a href="{% url "alliance.views.opportunity" pk=req.pk %}">
            {{ req.opportunity.label }}</a> &mdash; {{ req.skill.label }}</dd>
    {% empty %}
        <dd><i>None</i></dd>
    {% endfor %}
</dl>
{% endblock content %}

alliance/templates/base_site.html
{% comment %}

This is Alliance's default base_site.html. All Alliance templates ultimately
extend base_site, and this file provides a generic default for that. Sites
using the Alliance app may leave this be, or write their own base_site.html
in one of the site's TEMPLATE_DIRS directories. If Django finds a
base_site.html file in one of the TEMPLATE_DIRS, it will use that file instead
of this one. Note that the replacement file should be stored directly in the
template directory, not an alliance/ subfolder.

Alliance templates will expect base_site.html, wherever it is, to declare three
template blocks: title, extrahead, body, and content.

{% endcomment %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>{% block title %}{% endblock title %}</title>
{% block extrahead %}{% endblock extrahead %}
</head>
<body>
{% block body %}{% block content %}{% endblock content %}{% endblock body %}
</body>
</html>

alliance/templates/login.html
{% extends "alliance/base.html" %}

{% load url from future %}


{% block title %}Log in{% endblock title %}

{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock content %}